### PR TITLE
fixed meta-code generation for non-english host build context

### PR DESCRIPTION
**Pull request by chacha21**
Meta-code generation assumes a dot as decimal point, which is not the case in French, for instance. If the host build context is using a french locale, the project could not be built.

Adding a few `System.Globalization.CultureInfo.InvariantCulture` fixes the problem.

#1657

### CODE REVIEW

**Comment by chacha21** [comment]
@twsouthwick : how do I agree to the Contributor License Agreement  ?

**Comment by twsouthwick** [comment]
Docs are here: https://github.com/microsoft/contributorlicenseagreement?tab=readme-ov-file#accepting

**Review by twsouthwick — DISMISSED** [review]
LGTM - once the usings are added to simplify the names and the CLA is signed, I'll get it merged. Thanks @chacha21 for the fix!

**Comment by chacha21** [comment]
@microsoft-github-policy-service agree

**Comment by twsouthwick** [comment]
@microsoft-github-policy-service rerun

**Comment by twsouthwick** [comment]
@tomjebo the license/cla is not triggering - do you know who we can ask about that?

**Comment by tomjebo** [comment]
@twsouthwick re: CLA autotrigger, I just sent email to our dotnet org folks to see if it's something they can help with.

**Comment by DragosDanielBoia** [comment]
@dotnet-policy-service rerun

**Comment by chacha21** [comment]
@dotnet-policy-service agree

**Review by twsouthwick — APPROVED** [review]

**Pull request merged**
