### PR TITLE
Fix casing on customXml folder

### LINKED ISSUE #1350: CustomXmlPart incorrectly created as "customXML" rather than "customXml"
**Describe the bug**
When I create a new CustomXmlPart in an existing document it is created in "./customXML/item[id].xml" whereas 
word created the directory as "./customXml" rendering the document incomplete.

```csharp

var xmlPart =  """
<?xml version="1.0" encoding="UTF-8"?>
  <test:testCustom xmlns:test="http://testag.ch/testCustom">
    <test:CMX_LoremIpsum>
      <test:Para1>Lorem Ipsum</test:Para1>
      <test:Para2>Dolor sit amet</test:Para2>
      <test:Para3>Consectetur adipiscing elit</test:Para3>
      <test:Para4>den Rest müsste ich googlen</test:Para4>
    </test:CMX_LoremIpsum>
    <test:CMX_DummyTexts>
      <test:Text1>Some text for Field 'Text1'</test:Text1>
      <test:Text2>(ノಠ益ಠ)ノ彡┻━┻</test:Text2>
    </test:CMX_DummyTexts>
  </test:testCustom>
""";

var part = Document.GetOrCreateCmiCustomXmlPart();
using var partStream = part.GetStream(FileMode.Create,
                                              FileAccess.ReadWrite);

if (partStream.CanSeek)
            partStream.Seek(0, SeekOrigin.Begin);

var doc = XDocument.Parse(xmlPart);

using var xmlWriter = XmlWriter.Create(partStream);
doc.Save(xmlWriter);



    public static CustomXmlPart GetOrCreateCustomXmlPart(this WordprocessingDocument wordDoc,
                                                         string partId)
    {
        wordDoc.MainDocumentPart!.TryGetPartById(partId,
                                                 out var found);
        var part = found as CustomXmlPart;

        part ??= wordDoc.MainDocumentPart!.AddCustomXmlPart(CustomXmlPartType.CustomXml,
                                                            partId);

        var customXmlProps = part.CustomXmlPropertiesPart ?? part.AddNewPart<CustomXmlPropertiesPart>();
        customXmlProps.DataStoreItem ??= new DataStoreItem() { ItemId = Guid.NewGuid().ToString("B") };

        return part;
    }
```

**Observed behavior**
`AddCustomXmlPart` appears to create a new directory **customXML**:
```bash
├── [Content_Types].xml
├── customXml
│   ├── item1.xml
│   ├── item2.xml
│   ├── item3.xml
│   ├── item4.xml
│   ├── itemProps1.xml
│   ├── itemProps2.xml
│   ├── itemProps3.xml
│   ├── itemProps4.xml
│   └── _rels
│       ├── item1.xml.rels
│       ├── item2.xml.rels
│       ├── item3.xml.rels
│       └── item4.xml.rels
├── customXML
│   ├── item5.xml
│   ├── itemProps5.xml
│   └── _rels
│       └── item5.xml.rels
├── docProps
│   ├── app.xml
│   ├── core.xml
│   └── custom.xml
├── _rels
└── word
    ├── document.xml
    ├── fontTable.xml
    ├── glossary
    │   ├── document.xml
    │   ├── fontTable.xml
    │   ├── _rels
    │   │   └── document.xml.rels
    │   ├── settings.xml
    │   ├── styles.xml
    │   └── webSettings.xml
    ├── _rels
    │   └── document.xml.rels
    ├── settings.xml
    ├── styles.xml
    ├── theme
    │   └── theme1.xml
    └── webSettings.xml

12 directories, 32 files
```

**Expected behavior**
The new files should be created within **customXml**

```bash
.
├── [Content_Types].xml
├── customXml
│   ├── item1.xml
│   ├── item2.xml
│   ├── item3.xml
│   ├── item4.xml
│   ├── item5.xml
│   ├── itemProps1.xml
│   ├── itemProps2.xml
│   ├── itemProps3.xml
│   ├── itemProps4.xml
│   ├── itemProps5.xml
│   └── _rels
│       ├── item1.xml.rels
│       ├── item2.xml.rels
│       ├── item3.xml.rels
│       ├── item4.xml.rels
│       └── item5.xml.rels
├── docProps
│   ├── app.xml
│   ├── core.xml
│   └── custom.xml
├── _rels
└── word
    ├── document.xml
    ├── fontTable.xml
    ├── glossary
    │   ├── document.xml
    │   ├── fontTable.xml
    │   ├── _rels
    │   │   └── document.xml.rels
    │   ├── settings.xml
    │   ├── styles.xml
    │   └── webSettings.xml
    ├── _rels
    │   └── document.xml.rels
    ├── settings.xml
    ├── styles.xml
    ├── theme
    │   └── theme1.xml
    └── webSettings.xml

10 directories, 32 files
```

**Desktop (please complete the following information):**
 - OS: Windows Server 2022 / Fedora 37
 - Office version -
 - .NET Target: .NET Framework 4.8
 - DocumentFormat.OpenXml Version: 2.19.0

**Additional context**
Maybe it could be narrowed down to this:
https://github.com/dotnet/Open-XML-SDK/blob/d46f92b2963f1c21415be08fb21532306e55db75/test/DocumentFormat.OpenXml.Packaging.Tests/data/PartConstraintData.json#L281

### PR DESCRIPTION
**Pull request by mikeebowen**
Fixes #1350

### CODE REVIEW

**Comment by twsouthwick** [comment]
is there a change for the backend here?

**Comment by mikeebowen** [comment]
> is there a change for the backend here?

Yes, but it's not merged into main yet.

**Comment by twsouthwick** [comment]
It's helpful to link it here so we can easily compare the two (at least those who can see the backend)

**Comment by mikeebowen** [comment]
[customXml-capitalization](https://ointprotocol.visualstudio.com/OInteropTools/_git/OpenXML-Schemas/pullrequest/545)

**Review by tomjebo — DISMISSED** [review]

**Review by tomjebo — APPROVED** [review]

**Review by tomjebo — APPROVED** [review]

**Pull request merged**
