### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DraviaVemal**
Updated reference to OpenXML-Office library that's built on top of OpenXML SDK to provide option to create and manipulate office documents.

### CODE REVIEW

**Comment by twsouthwick** [comment]
LGTM - thanks for the PR and good luck with the project

**Review by tomjebo — APPROVED** [review]
Looks good. I'll check it out!

**Comment by DraviaVemal** [comment]
Is there any requirement missing to merge this PR ?

**Review by mikeebowen — APPROVED** [review]

**Comment by DraviaVemal** [comment]
Can anyone guide me what is required to get this PR merged?

**Pull request merged**
