### PR TITLE
API Rename to match XML ns

### PR DESCRIPTION
**Pull request by tomjebo**
this is a WIP. some samples not building still.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/Open-XML-SDK?pullRequest=1333) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/Open-XML-SDK?pullRequest=1333) before we can accept your contribution.<br/><br/>:x: tomjebo [sign now](https://cla.dotnetfoundation.org/dotnet/Open-XML-SDK?pullRequest=1333)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/Open-XML-SDK?pullRequest=1333) it.</sub>

**Comment by tomjebo** [comment]
I need to address the case on some names, specifically things like SpreadsheetML vs SpreadSheetML (the second "s" vs "S"). Which should we use? 

Also the ML (for Markup Language) where DocumentFormat.OpenXml uses lower case for the ml after X. Should we use Ml instead of ML? Acronyms in general, should we capitalize them or lower case like the SDK's name does?

Otherwise, the renaming is done.

**Comment by tomjebo** [comment]
this renaming will cause a lot of using and scoping changes in just about any project using the Open-XML-SDK. 
An alternative approach could be to limit the namespace changes to Office 2013 and later, leaving the Office 2007 and 2010 namespaces alone. Beyond 2013, we mainly see extensions and new features which still means a lot of code changes for consuming projects but not nearly as many as when we change (effectively) all the SDK namespaces.

**Comment by twsouthwick** [comment]
@tomjebo let's see if we can refactor things so that the namespace generation isn't done on the backend, but is configurable in the source generator here. It'll probably require some changes to how we structure the data files, but then we can look at enabling this change in some new Word/Excel/PPT assemblies (see https://github.com/dotnet/Open-XML-SDK/issues/1313#issuecomment-1462991520)

**Comment by tomjebo** [comment]
> @tomjebo let's see if we can refactor things so that the namespace generation isn't done on the backend, but is configurable in the source generator here. It'll probably require some changes to how we structure the data files, but then we can look at enabling this change in some new Word/Excel/PPT assemblies (see [#1313 (comment)](https://github.com/dotnet/Open-XML-SDK/issues/1313#issuecomment-1462991520))

I like it. I think we would mainly need to add the ns URI and the short ns name to the json stuff going to the front end, then on the front end have the mapping code do what NamespaceMappingData.xml and cs do now on the backend.

**Comment by tomjebo** [comment]
Sorry, the ns URI and prefixes are already on the front end. It's just the mapping of the ns shortnames to these.

**Comment by twsouthwick** [comment]
@tomjebo  I'm going to close this for now. If you identify things on the backend/sdk side that can be done feel free to open new issues/prs for those

**Pull request closed without merging**
